name: mid_card
description: A new Flutter project

# Flutter SDK version
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # other dependencies

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/log.png"


# Additional configuration if necessary



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image/angle.jpg
  #   - images/a_dot_ham.jpeg



  fonts:
  - family: pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: Source Code Pro
    fonts:
    - asset: fonts/SourceCodePro-VariableFont_wght.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
